import type { Card } from './card'

export const MOCK_CARDS: Card[] = [
  {
    id: '1',
    name: 'Soldat',
    hp: 5,
    armor: 1,
    attack: 2,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/a78925?text=Soldat',
    type: 'Mortal',
    elements: ['Neutral'],
    effects: 'Aucun effet spécial.',
    rarity: 'Common',
  },
  {
    id: '2',
    name: 'Héraclès',
    hp: 7,
    armor: 0,
    attack: 4,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/52297a?text=Héraclès',
    type: 'Hero',
    elements: ['Neutral'],
    effects: 'Aucun effet spécial.',
    rarity: 'Uncommon',
  },
  {
    id: '3',
    name: 'Cerbère',
    hp: 10,
    armor: 1,
    attack: 3,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/a78925?text=Cerbère',
    type: 'Monster',
    elements: ['Fire', 'Shadow'],
    effects: 'Aucun effet spécial.',
    rarity: 'Rare',
  },
  {
    id: '4',
    name: 'Hadès',
    hp: 14,
    armor: 2,
    attack: 5,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/06755b?text=Hadès',
    type: 'Olympian',
    effects: 'Aucun effet spécial.',
    elements: ['Shadow'],
    rarity: 'Epic',
  },
  {
    id: '5',
    name: 'Cronos',
    hp: 20,
    armor: 1,
    attack: 5,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/7d1212?text=Cronos',
    type: 'Primordial',
    elements: ['Neutral'],
    effects: 'Aucun effet spécial.',
    rarity: 'Legendary',
  },
  {
    id: '6',
    name: 'Icare',
    hp: 5,
    armor: 0,
    attack: 1,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/81a2b1?text=Icare',
    type: 'Mortal',
    effects: 'Aucun effet spécial.',
    elements: ['Neutral'],
    rarity: 'Uncommon',
  },
  {
    id: '7',
    name: 'Déméter',
    hp: 12,
    armor: 1,
    attack: 5,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/52297a?text=Déméter',
    type: 'Olympian',
    elements: ['Water'],
    effects: 'Aucun effet spécial.',
    rarity: 'Rare',
  },
  {
    id: '8',
    name: 'Minotaure',
    hp: 18,
    armor: 2,
    attack: 8,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/a78925?text=Minotaure',
    type: 'Monster',
    elements: ['Neutral'],
    rarity: 'Epic',
    effects: 'Aucun effet spécial.',
  },
  {
    id: '9',
    name: 'Bolina',
    hp: 8,
    armor: 0,
    attack: 1,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/a78925?text=Bolina',
    type: 'Hero',
    elements: ['Nature'],
    effects: 'Aucun effet spécial.',
    rarity: 'Uncommon',
  },
  {
    id: '10',
    name: 'Zeus, La tempête incarnée ultime',
    hp: 15,
    armor: 2,
    attack: 3,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/a78925?text=Zeus',
    type: 'Olympian',
    elements: ['Thunder'],
    effects: 'Aucun effet spécial.',
    rarity: 'Epic',
  },
  {
    id: '11',
    name: 'Apollon',
    hp: 10,
    armor: 1,
    attack: 3,
    imageUrl: 'https://placehold.co/400x560/1f1f1f/a78925?text=Apollon',
    type: 'Olympian',
    elements: ['Light'],
    effects:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    mechanics: ['Regeneration', 'Valor'],
    rarity: 'Rare',
  },
]
